# Generated by Django 4.1.10 on 2023-07-19 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageInPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Image_In_Post',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImagePost',
            fields=[
                ('imgpostid', models.CharField(db_column='ImgPostID', max_length=10, primary_key=True, serialize=False)),
                ('thumbnail_image', models.TextField(db_column='Thumbnail_image')),
                ('title', models.CharField(db_column='Title', max_length=255)),
                ('content', models.TextField(blank=True, db_column='Content', null=True)),
                ('post_time', models.DateTimeField(db_column='Post_time')),
            ],
            options={
                'db_table': 'Image_Post',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImageTable',
            fields=[
                ('imgid', models.CharField(db_column='ImgID', max_length=10, primary_key=True, serialize=False)),
                ('image_name', models.CharField(db_column='Image_name', max_length=255)),
                ('image_file', models.TextField(db_column='Image_file')),
                ('seed', models.CharField(blank=True, db_column='Seed', max_length=30, null=True)),
                ('steps', models.IntegerField(blank=True, db_column='Steps', null=True)),
                ('sampler', models.CharField(blank=True, db_column='Sampler', max_length=30, null=True)),
                ('cfg_scale', models.FloatField(blank=True, db_column='CFG_scale', null=True)),
                ('model_hash', models.CharField(blank=True, db_column='Model_hash', max_length=30, null=True)),
                ('clip_skip', models.IntegerField(blank=True, db_column='Clip_skip', null=True)),
                ('denoising_strength', models.FloatField(blank=True, db_column='Denoising_strength', null=True)),
                ('image_time', models.DateTimeField(db_column='Image_time')),
            ],
            options={
                'db_table': 'Image_Table',
                'managed': False,
            },
        ),
    ]
