# Generated by Django 4.1.10 on 2023-07-19 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_post_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageInPost',
        ),
        migrations.DeleteModel(
            name='ImagePost',
        ),
        migrations.DeleteModel(
            name='ImageTable',
        ),
    ]
